/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import ADT.ArrayList;
import ADT.List;
import ADT.SetListInterface;
import Control.ProgControl;
import Entity.TutorialGroup;
import Utility.JTableColumn;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OLIVER TAN ZU ZHUO
 */
public class ProgEditUI extends javax.swing.JFrame {

    ProgControl control;

    /**
     * Creates new form ProgEditUI
     */
    public ProgEditUI(ProgControl control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        durField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tutGrpTable = new javax.swing.JTable();
        addGrpBtn = new javax.swing.JButton();
        deleteGrpBtn = new javax.swing.JButton();
        codeField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Programme Name     :");

        jLabel4.setText("Programme Duration :");

        tutGrpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tutorial Group", "No. of Students"
            }
        ));
        jScrollPane1.setViewportView(tutGrpTable);
        if (tutGrpTable.getColumnModel().getColumnCount() > 0) {
            tutGrpTable.getColumnModel().getColumn(0).setResizable(false);
            tutGrpTable.getColumnModel().getColumn(1).setResizable(false);
        }

        addGrpBtn.setText("Add  Group");
        addGrpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGrpBtnActionPerformed(evt);
            }
        });

        deleteGrpBtn.setText("Remove Group");
        deleteGrpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGrpBtnActionPerformed(evt);
            }
        });

        codeField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        codeField.setText("AAA");
        codeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteGrpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addGrpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durField)
                                    .addComponent(nameField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(saveBtn)
                        .addGap(56, 56, 56)
                        .addComponent(deleteBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(durField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addGrpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteGrpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addGrpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGrpBtnActionPerformed
        control.addTutorialGroup();
    }//GEN-LAST:event_addGrpBtnActionPerformed

    private void deleteGrpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGrpBtnActionPerformed
        control.removeTutorialGroup(tutGrpTable.getSelectedRow());
    }//GEN-LAST:event_deleteGrpBtnActionPerformed

    private void codeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        control.saveData();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        control.deletePressed();
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGrpBtn;
    private javax.swing.JTextField codeField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteGrpBtn;
    private javax.swing.JTextField durField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable tutGrpTable;
    // End of variables declaration//GEN-END:variables

    public void initFields(String code, String name, String dur, SetListInterface<TutorialGroup> tutGrp) {
        codeField.setText(code);
        nameField.setText(name);
        durField.setText(dur);

        //set column height
        tutGrpTable.setRowHeight(25);

        //set column width 
        var width = jScrollPane1.getWidth();
        JTableColumn.setColumnWidthPercentage(tutGrpTable, width, 60, 40);

        tutGrpTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        setTableData(tutGrp);
    }

    public void setTableData(SetListInterface<TutorialGroup> tutGrp) {
        DefaultTableModel model = (DefaultTableModel) tutGrpTable.getModel();

        model.setRowCount(0);

        // Add data
        for (int i = 1; i <= tutGrp.size(); i++) {
            var grp = tutGrp.getEntry(i);
            Object[] rowData = {grp.getTutGrpCode(), grp.getTutGrpStudents().size()};
            model.addRow(rowData);
        }
    }

    public int confirmDialog() {
        return JOptionPane.showConfirmDialog(
                rootPane,
                "Save changes before closing window?",
                "Close Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
    }

    public int deleteDialog(String msg) {
        return JOptionPane.showConfirmDialog(
                rootPane,
                msg,
                "Delete Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
    }

    public List<String> getData() {
        List<String> data = new ArrayList();

        data.add(codeField.getText());
        data.add(nameField.getText());
        data.add(durField.getText());

        return data;
    }

    public void clearForm() {
        codeField.setText("");
        nameField.setText("");
        durField.setText("");
        
        DefaultTableModel model = (DefaultTableModel) tutGrpTable.getModel();
        model.setRowCount(0);
    }

    public String getSelectedData(int rowNum) {
        return String.valueOf(tutGrpTable.getValueAt(rowNum, 0));
    }
}
