/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import ADT.List;
import Control.ProgControl;
import Entity.Programme;
import Utility.JTableColumn;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OLIVER TAN ZU ZHUO
 */
public class ProgReportUI extends javax.swing.JFrame {

    ProgControl control;

    /**
     * Creates new form ProgReport
     */
    public ProgReportUI(ProgControl control) {
        this.control = control;
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        foundScroll = new javax.swing.JScrollPane();
        foundTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        dipScroll = new javax.swing.JScrollPane();
        dipTable = new javax.swing.JTable();
        degScroll = new javax.swing.JScrollPane();
        degTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Programme Report");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Foundation");

        foundTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Programme Code", "Programme Name", "Duration", "No. of Groups"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        foundScroll.setViewportView(foundTable);
        if (foundTable.getColumnModel().getColumnCount() > 0) {
            foundTable.getColumnModel().getColumn(0).setResizable(false);
            foundTable.getColumnModel().getColumn(1).setResizable(false);
            foundTable.getColumnModel().getColumn(2).setResizable(false);
            foundTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Diploma");

        dipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Programme Code", "Programme Name", "Duration", "No. of Groups"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dipScroll.setViewportView(dipTable);
        if (dipTable.getColumnModel().getColumnCount() > 0) {
            dipTable.getColumnModel().getColumn(0).setResizable(false);
            dipTable.getColumnModel().getColumn(1).setResizable(false);
            dipTable.getColumnModel().getColumn(2).setResizable(false);
        }

        degTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Programme Code", "Programme Name", "Duration", "No. of Groups"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        degScroll.setViewportView(degTable);
        if (degTable.getColumnModel().getColumnCount() > 0) {
            degTable.getColumnModel().getColumn(0).setResizable(false);
            degTable.getColumnModel().getColumn(1).setResizable(false);
            degTable.getColumnModel().getColumn(2).setResizable(false);
            degTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Degree");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(268, 268, 268))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dipScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(foundScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(degScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foundScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dipScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane degScroll;
    private javax.swing.JTable degTable;
    private javax.swing.JScrollPane dipScroll;
    private javax.swing.JTable dipTable;
    private javax.swing.JScrollPane foundScroll;
    private javax.swing.JTable foundTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    public void setFoundationData(List<Programme> foundList) {
        setTableData(foundTable, foundList);
    }

    public void setDiplomaData(List<Programme> dipList) {
        setTableData(dipTable, dipList);
    }

    public void setDegreeData(List<Programme> degList) {
        setTableData(degTable, degList);
    }

    private void setTableData(JTable table, List<Programme> list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        model.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            var program = list.get(i);
            Object[] rowData = {program.getProgramCode(), program.getProgramName(), program.getProgramDuration(), program.getTutGroups().size()};
            model.addRow(rowData);
        }
    }
    
    private void initTable() {
        //set column height
        foundTable.setRowHeight(25);

        //set column width 
        var width = foundScroll.getWidth();
        JTableColumn.setColumnWidthPercentage(foundTable, width, 20, 40, 20,20);

        foundTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        //set column height
        dipTable.setRowHeight(25);
        JTableColumn.setColumnWidthPercentage(dipTable, width, 20, 40, 20,20);

        dipTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        //set column height
        degTable.setRowHeight(25);
        JTableColumn.setColumnWidthPercentage(degTable, width, 20, 40, 20,20);

        degTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

}
